''' PROBLEM #44:
Pentagonal numbers are generated by the formula, Pn=n(3n1)/2. The first ten pentagonal numbers are:
1, 5, 12, 22, 35, 51, 70, 92, 117, 145, ...
It can be seen that P4 + P7 = 22 + 70 = 92 = P8. However, their difference, 70  22 = 48, is not pentagonal.
Find the pair of pentagonal numbers, Pj and Pk, for which their sum and difference is pentagonal and D = |Pk  Pj| is minimised; what is the value of D?
'''


def main():

    plst = []
    potentials = []

    min_pq = (0,0)
    min_d = float("inf")

    n = 0
    while 1:
        n += 1
        p = n * (3 * n - 1) / 2
        print p
        
        i=0
        while i < len(potentials):
            a,b = potentials[i]
            if a+b <= p:
                if a+b == p:
                    if b-a < min_d:
                        print "\t", a, b
                        min_pq = (a,b)
                        min_d = b-a
                del potentials[i]
                continue
            i += 1
        
        if  not plst or p - plst[-1] < min_d:
        
            for q in plst:
                d = p - q
                for r in plst:
                    if r >= d:
                        if r == d:
                            potentials.append((q, p))
                        break
                        
        elif not potentials:
            break
        
        plst.append(p)

    answer = min_d

    print answer

if __name__=='__main__':
    main()
